package:
  name: "or-datasets"
  version: {{ version }}

source:
  path: ../

build:
  noarch: generic
  script: python setup.py install

requirements:
  build:
    - python {{ python }}
    - setuptools
    - wheel
  run:
    - python {{ python }}

test:
  imports:
    - or_datasets

about:
  home: https://github.com/flowty/or-datasets
  license: MIT
  license_file: LICENSE
  summary: OR Datasets
  doc_url: https://github.com/flowty/or-datasets
