name: Python Deploy CI

on: [workflow_dispatch]
  
jobs:
  pypi:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Get version
      id: get_version
      run: |
        export PACKAGE_VERSION=$(echo ${GITHUB_REF:11} | cut -d "/" -f2)
        echo ::set-output name=version::$PACKAGE_VERSION
        echo PACKAGE_VERSION=$PACKAGE_VERSION
    # get latest release
    - name: Get artifact name
      id: artifact_name
      run: |
        export RESPONSE=$(curl -vLJ -u github_flowty:${{ secrets.FLOWTY_GITHUB_TOKEN }} https://api.github.com/repos/flowty/or-datasets/releases/latest)
        eval $(echo "$RESPONSE" | grep -C3 "name.:.\+wheel" | grep -w id | tr : = | tr -cd '[[:alnum:]]=')
        echo ::set-output name=ARTIFACT_ID::$id
        export VERSION=$(echo "$RESPONSE" | grep -C3 "tag_name.:.\+version" | grep -w tag_name | cut -d "/" -f2 | cut -d "\"" -f1)
        echo ::set-output name=VERSION::$VERSION
        echo VERSION=$VERSION
        [[ $VERSION == ${{ steps.get_version.outputs.version }} ]]
    - name: Get artifact
      run: |
        curl -vLJ -H 'Accept: application/octet-stream' -u github_flowty:${{ secrets.FLOWTY_GITHUB_TOKEN }} -o wheel.zip https://api.github.com/repos/flowty/or-datasets/releases/assets/${{steps.artifact_name.outputs.ARTIFACT_ID}}
    - name: Unzip
      run: |
        mkdir dist
        unzip wheel.zip -d dist/
    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        pip install twine
    - name: What wheel is here
      run: ls -l dist/
    - name: Twine check
      run: |
        twine check dist/*
    - name: Upload
      run: |
        twine upload dist/* -u __token__ -p ${{secrets.PYPI_APITOKEN}}
    - name: Install
      run: |
        for i in 1 2 3 4 5; do pip install or-datasets==${{ steps.get_version.outputs.version }} && break || sleep 15; done
